###
POST http://localhost:8080/api/users/1/words
Content-Type: application/json
Authorization: Basic user password

[
  {
    "spelling": "test",
    "meaning": "test",
    "reading": "test"
  },
  {
    "spelling": "test2",
    "meaning": "test2",
    "reading": "test2"
  }
]

###
GET http://localhost:8080/api/users/1/words
Accept: application/json
Authorization: Basic user2 password

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user",
  "password": "password",
  "email": "email@email.com"
}