server:
  error:
    whitelabel:
      enabled: false

debug: true
logging:
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure: error
spring:
  data:
    mongodb:
      database: ${MONGO_DB:changeit}
      port: ${MONGO_PORT:27017}
